name: Test

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install PNPM
      run: npm i -g pnpm

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Build
      run: pnpm build

    - name: Test
      run: pnpm test
